Added support for appending a suffix to the key route in the KeyRouter
terascope/standard-assets pull request #659
Opened 2022-09-28 23:59 UTC by jeffmontagna

- Added option `suffix_use` to append a suffix to the routing key
- Added optional suffix values for `suffix_upper`, `suffix_lower`, `suffix_number`, and `suffix_other`
- Example to only append a suffix for uppercase routing keys
```json
{
  "_op": "key_router",
  "use": 1
  "from": "beginning",
  "suffix_use": true,
  "suffix_upper": "--u",
} 
```
- Example to only append suffixes for all routing keys
```json
{
  "_op": "key_router",
  "use": 1
  "from": "beginning",
  "suffix_use": true,
  "suffix_upper": "--u",
  "suffix_lower": "--l",
  "suffix_number": "--n",
  "suffix_other":  "--c"
} 
```

refs #373

2022-09-29 18:25 UTC, godber commented
So what is the behavior of this code when the job contains:

```
{
  "_op": "key_router",
  "use": 1
  "from": "beginning",
  "suffix_use": true
} 
```

2022-09-30 18:14 UTC, godber commented
We're a little conflicted on what appropriate defaults might be for this, for example when ` "suffix_use": true,` should that be an error, or should it be one of the following three scenarios:

## Option 1 - everything gets a suffix

* `index-a--u`
* `index-a--l`
* `index-5--n`
* `index-_--c`

## Option 2 - Just the letters get a suffix

* `index-a--u`
* `index-a--l`
* `index-5`
* `index-_`

## Option 3 - Just uppercase get a suffix

* `index-a--u`
* `index-a`
* `index-5`
* `index-_`

I think we should just consider it an error if `"suffix_use": true`  and no other choice is made.  And lets not overthink the usability of something that doesn't get a whole lot of use.

2022-09-30 18:16 UTC, godber commented
There's a strong argument for the Option 1 above due to how these indices will get used in our internal use cases.  Just having index names with consistent structures is desirable.

2022-10-03 20:23 UTC, jsnoble requested changes

2022-10-03 20:23 UTC, jsnoble commented on packages/standard-asset-apis/test/routers/KeyRouter-spec.ts
> +        expect(router.lookup(entity)).toEqual('R--u');
how is this equal to `R--u`? Since you have the caseFn called on the outer return value from the suffix method, should this not be `R--U`?

2022-10-03 20:58 UTC, jsnoble approved these changes
LGTM

2022-10-03 20:59 UTC, merged