Migrate to esm
terascope/standard-assets pull request #860
Opened 2024-06-26 22:28 UTC by sotojn

TBD

2024-06-29 01:31 UTC, sotojn commented
This issue has validation that this asset is working correctly: #861

2024-07-01 21:30 UTC, jsnoble requested changes
The move to switch out pulling types from job-components to the types package is not fully needed now as it has been refactored and the types of the two libraries work with each other now but its ok, the only thing is the commented out code left in

2024-07-01 21:30 UTC, jsnoble commented on jest.config.js
> +        // '<rootDir>/test/routed_sender/schema-spec.{ts,js}',
I don't think we need this right? should not be commented out

2024-07-02 16:53 UTC, jsnoble approved these changes

2024-07-02 16:54 UTC, merged